GET http://localhost:3004/api/users

###
GET http://localhost:3004/api/users/by/username/johndoe
###
GET http://localhost:3004/api/users/by/username/johndor?x=777&y=fjkdj
###
GET http://localhost:3004/api/users/by?usernames=johndoejr,johndoe
###  GET (error)
GET http://localhost:3004/api/users/by?names=nimi1,nimi2
### DELETE
DELETE http://localhost:3004/api/user/joöhnsr_iv

###
PUT http://localhost:3004/api/user/joöhnsr_4
Content-Type: application/json

{
  "fullname": "Firsname Lastname",
  "email": "u@mail.com",
  "__v": 0
}

### CREATE

POST http://localhost:3004/api/users
Content-Type: application/json

{
    "name": {
        "first": "Bob",
        "last" : "Doe"
    },
    "username" : "bobdoe",
    "email" : "b.doe.jr@email.com"
        

}

###
POST http://localhost:3004/api/posts/
Content-Type: application/json

{
    "authorId" : "5fcce2097838c4acd66ac06e",
    "text" : "Mongoose also supports populating virtuals. A populated virtual contains documents from another collection. To define a populated virtual..."
}
###
GET http://localhost:3004/api/posts/5fcd350fdfe163c8b2c5cd9b
