GET http://localhost:3000/api/members

###

GET http://localhost:3000/api/members/e87ef18c-82da-40e7-a9ff-a5d75c15e74f

### CREATE NEW MEMBER, CORRECT REQUEST
POST http://localhost:3000/api/members/
Content-Type: application/json

{ "id":"3", "name": "John Doe Jr", "email": "jd.jr@email.com", "status":"a"}

### name, email missing

POST http://localhost:3000/api/members/
Content-Type: application/json

{ "id":"3", "email": "jd.jr@email.com", "status":"a"}


### email missing

POST http://localhost:3000/api/members/
Content-Type: application/json

{ "id":"3", "name": "John Doe Jr",  "status":"a"}

