### (1) REGISTER A NEW MEMBERSHIP ###################################################
POST http://localhost:3005/memberships
Content-Type: application/json

{
    "member_name" : "Harry"
}

### Response:

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 436
ETag: W/"1b4-CwLNII7aV08Bd6BOwzH+2AON3Kc"
Date: Wed, 16 Dec 2020 18:33:26 GMT
Connection: close

{
  "data": {
    "redemptions": [],
    "_id": "5fda52f6e2228a8800f3119f",
    "member_name": "Harry",
    "valid_until": "2021-01-15T18:33:26.203Z",
    "qr_code_value": "682ca052-4876-4841-8587-77d80cb9667d",
    "__v": 0,
    "is_valid": true,
    "number_of_redemptions_today": 0,
    "minutes_since_last_redemption": null,
    "can_redeem": true,
    "qr_code_url": "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=682ca052-4876-4841-8587-77d80cb9667d",
    "id": "5fda52f6e2228a8800f3119f"
  }
}




### (2.1) Create a Drink Order ###################################################
POST http://localhost:3005/orders
Content-Type: application/json

{
    "drink" : "CAFE MOCCA"
}


### Response:

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 165
ETag: W/"a5-RnXGePKP0wYJdfTQgGlH5fQIh1U"
Date: Wed, 16 Dec 2020 18:34:51 GMT
Connection: close

{
  "data": {
    "_id": "5fda534be2228a8800f311a0",
    "drink": "CAFE MOCCA",
    "createdTime": "2020-12-16T18:34:51.869Z",
    "__v": 0,
    "is_redeemed": false,
    "id": "5fda534be2228a8800f311a0"
  }
}

### (2.2) Redeem a Drink (order) ###################################################

POST http://localhost:3005/orders/5fda534be2228a8800f311a0/redemption/
Content-Type: application/json

{
  "membership_qr_code" : "682ca052-4876-4841-8587-77d80cb9667d"
}

### OK Response:
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 422
ETag: W/"1a6-D6YCdQfuUIihYjHrxnA6bhZZ7+Y"
Date: Wed, 16 Dec 2020 18:37:30 GMT
Connection: close

{
  "message": "Order successfully redeemed",
  "order": {
    "_id": "5fda534be2228a8800f311a0",
    "drink": "CAFE MOCCA",
    "createdTime": "2020-12-16T18:34:51.869Z",
    "__v": 0,
    "redemption": {
      "_id": "5fda53eae2228a8800f311a1",
      "order_id": "5fda534be2228a8800f311a0",
      "time": "2020-12-16T18:37:30.628Z",
      "__v": 0
    },
    "redeemed_by_member_name": "Harry",
    "redeemed_by_membership_id": "5fda52f6e2228a8800f3119f",
    "is_redeemed": true,
    "id": "5fda534be2228a8800f311a0"
  }
}

### ERROR - Order already redeemed

HTTP/1.1 409 Conflict
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 74
ETag: W/"4a-TQ7vc7CRzI6DNuH0ZPEL40YYFac"
Date: Tue, 15 Dec 2020 13:57:15 GMT
Connection: close

{
  "message": "Order is already redeemed and cannot be redeemed more times!"
}

### ERROR - Too many redemptions
HTTP/1.1 403 Forbidden
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 713
ETag: W/"2c9-aP3pwiBQwInQVS91CCmmTK4DL70"
Date: Tue, 15 Dec 2020 13:58:52 GMT
Connection: close

{
  "message": "Member is not allowed to redeem a drink at this time. Only 1 drink is allowed every 30 minutes, and up to 5 times per day. Please try again later.",
  "membership": {
    "redemptions": [
      {
        "_id": "5fd8c0a2a3d17e192e382b95",
        "time": "2020-12-15T13:56:50.918Z",
        "order_id": "5fd8bf2ba1df8118b5e6d667",
        "__v": 0
      }
    ],
    "_id": "5fd8bf08a1df8118b5e6d666",
    "member_name": "ELIAS",
    "valid_until": "2021-01-14T13:50:00.995Z",
    "qr_code_value": "e177ad5d-978f-40e3-b99f-87bac5b1449b",
    "__v": 1,
    "is_valid": true,
    "number_of_redemptions_today": 1,
    "minutes_since_last_redemption": 2,
    "can_redeem": false,
    "qr_code_url": "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=e177ad5d-978f-40e3-b99f-87bac5b1449b",
    "id": "5fd8bf08a1df8118b5e6d666"
  }
}