### REQUEST A NEW MEMBERSHIP
### 
###
###
POST http://localhost:3005/memberships
Content-Type: application/json

{
    "member_name" : "ELIAS"
}

###
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 436
ETag: W/"1b4-PKnQBfPrW+NGNC9FEuNxvWbsXbA"
Date: Tue, 15 Dec 2020 13:50:01 GMT
Connection: close

{
  "data": {
    "redemptions": [],
    "_id": "5fd8bf08a1df8118b5e6d666",
    "member_name": "ELIAS",
    "valid_until": "2021-01-14T13:50:00.995Z",
    "qr_code_value": "e177ad5d-978f-40e3-b99f-87bac5b1449b",
    "__v": 0,
    "is_valid": true,
    "number_of_redemptions_today": 0,
    "minutes_since_last_redemption": null,
    "can_redeem": true,
    "qr_code_url": "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=e177ad5d-978f-40e3-b99f-87bac5b1449b",
    "id": "5fd8bf08a1df8118b5e6d666"
  }
}


### CREATE AN ORDER FOR A DRINK
POST http://localhost:3005/orders
Content-Type: application/json

{
    "drink" : "CAFE MOCCA for Elias (2)"
}

###

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 175
ETag: W/"af-BcCjmlEo5BputT/cIOynW2cgj6c"
Date: Tue, 15 Dec 2020 13:50:35 GMT
Connection: close

{
  "data": {
    "_id": "5fd8bf2ba1df8118b5e6d667",
    "drink": "More CAFE MOCCA for Elias",
    "createdTime": "2020-12-15T13:50:35.236Z",
    "__v": 0,
    "is_redeemed": false,
    "id": "5fd8bf2ba1df8118b5e6d667"
  }
}

### Second order...

HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 179
ETag: W/"b3-aN39cV3XeZLneLglbiQZkOKAYO4"
Date: Tue, 15 Dec 2020 13:58:16 GMT
Connection: close

{
  "data": {
    "_id": "5fd8c0f8a3d17e192e382b97",
    "drink": "CAFE MOCCA for Elias (2)",
    "createdTime": "2020-12-15T13:58:16.247Z",
    "__v": 0,
    "is_redeemed": false,
    "id": "5fd8c0f8a3d17e192e382b97"
  }
}

### REDEEM COFFEE ORDER USING A VALID MEMBERSHIP
GET http://localhost:3005/orders/5fd8c0f8a3d17e192e382b97/redemption/e177ad5d-978f-40e3-b99f-87bac5b1449b

### SUCCESS
HTTP/1.1 200 OK
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 432
ETag: W/"1b0-N6o+oputa/tu+le2iNfRiS8RGzs"
Date: Tue, 15 Dec 2020 13:56:50 GMT
Connection: close

{
  "message": "Order successfully redeemed",
  "order": {
    "_id": "5fd8bf2ba1df8118b5e6d667",
    "drink": "CAFE MOCCA for Elias",
    "createdTime": "2020-12-15T13:50:35.236Z",
    "__v": 0,
    "redemption": {
      "_id": "5fd8c0a2a3d17e192e382b95",
      "time": "2020-12-15T13:56:50.918Z",
      "order_id": "5fd8bf2ba1df8118b5e6d667",
      "__v": 0
    },
    "redeemed_by_member_name": "ELIAS",
    "redeemed_by_membership_id": "5fd8bf08a1df8118b5e6d666",
    "is_redeemed": true,
    "id": "5fd8bf2ba1df8118b5e6d667"
  }
}

### ERROR - Order already redeemed

HTTP/1.1 409 Conflict
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 74
ETag: W/"4a-TQ7vc7CRzI6DNuH0ZPEL40YYFac"
Date: Tue, 15 Dec 2020 13:57:15 GMT
Connection: close

{
  "message": "Order is already redeemed and cannot be redeemed more times!"
}

### ERROR - Too many redemptions
HTTP/1.1 403 Forbidden
X-Powered-By: Express
Content-Type: application/json; charset=utf-8
Content-Length: 713
ETag: W/"2c9-aP3pwiBQwInQVS91CCmmTK4DL70"
Date: Tue, 15 Dec 2020 13:58:52 GMT
Connection: close

{
  "message": "Member is not allowed to redeem a drink at this time. Only 1 drink is allowed every 30 minutes, and up to 5 times per day. Please try again later.",
  "membership": {
    "redemptions": [
      {
        "_id": "5fd8c0a2a3d17e192e382b95",
        "time": "2020-12-15T13:56:50.918Z",
        "order_id": "5fd8bf2ba1df8118b5e6d667",
        "__v": 0
      }
    ],
    "_id": "5fd8bf08a1df8118b5e6d666",
    "member_name": "ELIAS",
    "valid_until": "2021-01-14T13:50:00.995Z",
    "qr_code_value": "e177ad5d-978f-40e3-b99f-87bac5b1449b",
    "__v": 1,
    "is_valid": true,
    "number_of_redemptions_today": 1,
    "minutes_since_last_redemption": 2,
    "can_redeem": false,
    "qr_code_url": "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=e177ad5d-978f-40e3-b99f-87bac5b1449b",
    "id": "5fd8bf08a1df8118b5e6d666"
  }
}