POST http://localhost:3005/orders
Content-Type: application/json

{
    "drink" : "CAFE LATTE"
}
###
POST http://localhost:3005/orders/5fda546fe2228a8800f311a4/redemption
Content-Type: application/json

{
    "membership_qr_code" : "682ca052-4876-4841-8587-77d80cb9667d"
}
###
GET http://localhost:3005/orders/5fd8a0b93c1b9a0faeb949ab
###
